name: bayt_al_attar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  # مكتبات فايربيس (تم استبدال Firestore بـ Realtime Database)
  firebase_core: ^3.8.0
  firebase_database: ^11.1.0
  # المكتبات الأخرى
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true